[package]
name = "capwat-server"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
capwat-api-types    = { workspace = true, features = ["server"] }
capwat-config       = { workspace = true }
capwat-crypto       = { workspace = true, features = ["server"] }
capwat-db           = { workspace = true }
capwat-error        = { workspace = true, features = ["server"] }
capwat-macros       = { workspace = true }
capwat-model        = { workspace = true }
capwat-tracing      = { workspace = true }
capwat-vfs          = { workspace = true }
capwat-utils        = { workspace = true }

bitflags.workspace           = true
bon.workspace                = true
chrono.workspace             = true
futures.workspace            = true
serde.workspace              = true
serde_json.workspace         = true
thiserror.workspace          = true
tokio.workspace              = true
tracing.workspace            = true
tracing-subscriber.workspace = true
uuid.workspace               = true

bytes        = "1.9.0"
jsonwebtoken = "9.3.0"
validator    = "0.19.0"

# http crates
axum            = { workspace = true }
axum-client-ip  = "0.6.1"
axum-extra      = { version = "0.9.4", features = ["typed-header"] }
tower           = "0.5.1"

[dependencies.tower-http]
version = "0.6.1"
features = [
    "add-extension",
    "catch-panic",
    "compression-full",
    "limit",
    "request-id",
    "sensitive-headers",
    "timeout",
    "trace"
]

[dev-dependencies]
axum-test = "16.4.0"
assert-json-diff = "*"
static_assertions.workspace = true
