[package]
name = "capwat-types-derive-lib"
description = "Separate library to test macros :)"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
syn.workspace = true
quote.workspace = true

[lints]
workspace = true
