## You can also use environment variables if you don't prefer to put some
## values in a config file. Loading environment variables with `.env` file
## is also supported.
##
## Please refer to the wiki for instructions on how to configure Capwat
## server using environment variables.
##
## Capwat will try to find files like `config.toml` or `capwat.toml` and
## load using the file in your current working directory. If you want to point
## the config file for Capwat, you can use `` and set the
## value to where your config file is located.

# These keys under auth table are very sensitive! If you try to compromise
# or leak all/some of your keys, you are risking all of your users' session
# token to be accessible to the public.
[auth]
jwt_key = "w@XuJ!iCoM#rh%LcjeADt^SC"

[db]
enforce_tls = true
timeout_secs = 5

[db.primary]
readonly = false
min_idle = 5
pool_size = 20
