[package]
name = "whim"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# local crates
validator.workspace = true

# crypto
jsonwebtoken = "9.1.0"
sha2 = "0.10.8"

# useful utilities
error-stack = { version = "0.4.1" }
futures = "0.3.29"
heck = "0.4.1"
hex = "0.4.3"
once_cell = "1.18.0"
thiserror = "1.0.50"

# systems
actix-web = { version = "4.4.0", default-features = false, features = ["rustls"] } # I don't think actix is part of it
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["full"] }

# generators
random-string = "1.0.1"

# validation
regex = "1.10.2"

# telemetry and logging
tracing = "0.1.40"
tracing-actix-web = "0.7.9"
tracing-error = "0.2.0"

# de/serialization
figment = { version = "0.10.12", features = ["env", "toml", "test"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde-value = "0.7.0"
toml_edit = { version = "0.21.0", features = ["serde"] }

# testing
serde_test = "1.0.176"
static_assertions = "1.1.0"

# database
sqlx = { version = "0.7.2", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono"] }

# data types
chrono = { version = "0.4.31", features = ["serde"] }
either = "1.9.0"
mime = "0.3.17"
url = "2.4.1"
tracing-subscriber = "0.3.18"

[lints]
workspace = true

##################
# whim workspace #
##################
[workspace]
members = ["crates/*"]
resolver = "2"

##########################
# workspace dependencies #
##########################
[workspace.dependencies]
validator = { path = "crates/validator" }

once_cell = "1.18.0"
serde = { version = "1.0.190", features = ["derive"] }
url = "2.4.1"

proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"

#########################
# package configuration #
#########################
[workspace.package]
version = "0.0.1-alpha.0"
authors = ["memothelemo <me@memothelemo.xyz>"]
edition = "2021"
license = "AGPL-2.0"
repository = "https://github.com/memothelemo/whim"
rust-version = "1.73.0"

######################
# lint configuration #
######################
[workspace.lints.clippy]
default_trait_access = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"

expect_used = "deny"
let_underscore_must_use = "deny"
pedantic = "deny"
too_many_lines = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
nonstandard_style = "deny"
rust_2018_idioms = "deny"
