[workspace]
members = [
    "src/core",
    "src/database",
    "src/http-server",
    "src/library/*",
    "src/macros/*",
    "src/types",
]
resolver = "2"

[workspace.package]
version = "0.0.1-alpha.0"
authors = ["memothelemo <me@memothelemo.xyz>"]
edition = "2021"
license = "AGPL-2.0"
repository = "https://github.com/memothelemo/whim"
rust-version = "1.73.0"

[workspace.dependencies]
# crypto
jsonwebtoken = "9.1.0"
sha2 = "0.10.8"

# useful utilities
error-stack = { version = "0.4.1", features = ["spantrace"] }
futures = "0.3.29"
hex = "0.4.3"
once_cell = "1.18.0"
thiserror = "1.0.50"

# systems
actix-web = { version = "4.4.0", default-features = false, features = ["rustls"] } # I don't think actix is part of it
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["full"] }

# generators
random-string = "1.0.1"

# validation
regex = "1.10.2"

# telemetry and logging
tracing = "0.1.40"
tracing-error = "*"

# de/serialization
figment = { version = "0.10.12", features = ["env", "toml", "test"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde-value = "0.7.0"
toml_edit = { version = "0.20.7", features = ["serde"] }

serde_test = "1.0.176"

# data types
chrono = { version = "0.4.31", features = ["serde"] }
either = "1.9.0"
mime = "0.3.17"
url = "2.4.1"

# whim core libraries
sensitive = { path = "src/library/sensitive" }
validator = { path = "src/library/validator" }

# whim sub-crates
whim-core = { path = "src/core" }
whim-database = { path = "src/database" }
whim-types = { path = "src/types" }

# database
sqlx = { version = "0.7.2", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono"] }

# macros
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"

whim-derives = { path = "src/macros/derives" }
