[workspace]
resolver = "2"

[workspace.package]
version = "0.0.1-alpha.0"
authors = ["memothelemo <me@memothelemo.xyz>"]
edition = "2021"
license = "AGPL-2.0"
repository = "https://github.com/memothelemo/whim"
rust-version = "1.73.0"

[package]
name = "whim"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# axum = { version = "0.6.20", default-features = false, features = ["tracing", "tokio", "tower-log", "query", "json", "http1"] }
chrono = { version = "0.4.31", features = ["serde"] }
figment = { version = "0.10.12", features = ["env", "yaml", "test"] }
once_cell = "1.18.0"
serde = { version = "1.0.190", features = ["derive"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "tls-rustls", "postgres", "chrono"] }
tokio = { version = "1.33.0", features = ["full"] }

sensitive = { path = "library/sensitive" }
validator = { path = "library/validator" }
thiserror = "1.0.50"
error-stack = { version = "0.4.1", features = ["spantrace"] }
dotenvy = "0.15.7"
tracing = "0.1.40"
regex = "1.10.2"
sha2 = "0.10.8"
actix-web = { version = "4.4.0", default-features = false, features = ["rustls"] }
serde_json = "1.0.108"
tracing-subscriber = "0.3.17"
jsonwebtoken = "9.1.0"
futures-util = "0.3.29"
hex = "0.4.3"

