[workspace]
members = [
    "core/*",
    "main/api/*",
    "main/database"
]
resolver = "2"

[workspace.package]
authors = ["memothelemo <me@memothelemo.xyz>"]
edition = "2021"
license = "AGPL-2.0"
repository = "https://github.com/capwat/backend"
version = "0.0.1-alpha.0"
rust-version = "1.74.0"

[workspace.dependencies]
capwat-diesel = { path = "core/diesel-impl" }
capwat-kernel = { path = "core/kernel" }
capwat-types-common = { path = "core/types-common" }
capwat-types-v1 = { path = "core/types-v1" }

async-trait = "0.1.74"
cfg-if = "1.0.0"
chrono = "0.4.31"
dotenvy = "0.15.7"
either = "1.9.0"
error-stack = { git = "https://github.com/memothelemo/error-stack", rev = "3c4b10" }
futures = "0.3.29"
mime = "0.3.17"
once_cell = "1.19.0"
heck = "0.4.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_test = "1.0.176"
static_assertions = "1.1.0"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-error = "0.2.0"
url = "2.5.0"

# we have no choice :)
diesel = { version = "2.1.4", features = ["chrono", "postgres"] }
diesel_derives = { version = "2.1.2", features = ["postgres"] }

# macro dependencies
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.48"

# for capwat api
actix-web = { version = "4.4.1", features = ["rustls-0_21"] }

[workspace.lints.clippy]
# too pedantic
doc_markdown = "allow"
module_name_repetitions = "allow"
wildcard_imports = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

let_underscore_must_use = "warn"
non_ascii_literal = "warn"
pedantic = "warn"
unwrap_used = "warn"

[workspace.lints.rust]
rust_2018_idioms = "warn"
unused = "warn"
