edition = "2021"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# nightly/unstable features
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_arm_blocks = true
normalize_comments = true
overflow_delimited_expr = true
struct_lit_single_line = false
