[package]
name = "validator"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["derive"]
derive = ["validator-derive"]

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
url = "2.4.1"
validator-derive = { path = "../validator-derive", optional = true }
