[package]
name = "capwat-s3-driver"
description = "Capwat's storage driver with S3"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
