[package]
name = "validator-derive"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
once_cell = "1.18.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"
