[package]
name = "capwat-model"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
capwat-api-types = { workspace = true, features = ["server"] }
capwat-crypto.workspace = true
capwat-db.workspace = true
capwat-error.workspace = true
capwat-macros.workspace = true
capwat-utils.workspace = true

bon.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

sea-query = { version = "0", features = ["backend-postgres", "with-chrono"] }
sea-query-binder = { version = "0.7.0", features = ["sqlx-postgres", "with-chrono", "runtime-tokio-rustls"] }
sqlx.workspace = true

[dev-dependencies]
capwat-tracing.workspace = true
capwat-vfs.workspace = true
tokio.workspace = true

[lints]
workspace = true
