[package]
name = "capwat-model"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
capwat-api-types = { workspace = true, features = ["server"] }
capwat-db.workspace = true
capwat-error.workspace = true
capwat-utils.workspace = true

bon.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

diesel.workspace = true
diesel-async.workspace = true
diesel_async_migrations = "0.15.0"
diesel-derive-newtype.version = "2.1.2"
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }

[lints]
workspace = true
