[package]
name = "whim-derives"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
once_cell.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
