[package]
name = "capwat-kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
grpc = ["percent-encoding", "prost", "tonic", "tonic-build"]

[dependencies]
async-trait.workspace = true
capwat-types = { workspace = true, features = ["server_impl"] }
chrono.workspace = true
error-stack.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-error.workspace = true
url.workspace = true
validator.workspace = true

percent-encoding = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }

[build-dependencies]
tonic-build = { workspace = true, optional = true }

[dev-dependencies]
serde_test.workspace = true
static_assertions.workspace = true

[lints]
workspace = true
