[package]
name = "sensitive"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
validator = { path = "../validator" }
