pub const CONSOLE_LOGGING_STREAM: &str = "CAPWAT_CONSOLE_LOGGING_STREAM";
pub const CONSOLE_LOGGING_STYLE: &str = "CAPWAT_CONSOLE_LOGGING_STYLE";
pub const CONSOLE_LOGGING_TARGETS: &str = "CAPWAT_CONSOLE_LOGGING_TARGETS";

pub const FILE_LOGGING_ROTATION_INTERVAL: &str = "CAPWAT_FILE_LOGGING_ROTATION_INTERVAL";
pub const FILE_LOGGING_ENABLED: &str = "CAPWAT_FILE_LOGGING_ENABLED";
pub const FILE_LOGGING_OUTPUT: &str = "CAPWAT_FILE_LOGGING_OUTPUT";
pub const FILE_LOGGING_STYLE: &str = "CAPWAT_FILE_LOGGING_STYLE";
pub const FILE_LOGGING_TARGETS: &str = "CAPWAT_FILE_LOGGING_TARGETS";

pub const LOGGING_GLOBAL_STYLE: &str = "CAPWAT_LOGGING_GLOBAL_STYLE";
pub const LOGGING_GLOBAL_TARGETS: &str = "CAPWAT_LOGGING_GLOBAL_TARGETS";

pub const SERVER_CONFIG_FILE: &str = "CAPWAT_SERVER_CONFIG";
pub const SERVER_IP: &str = "CAPWAT_SERVER_IP";
pub const SERVER_PORT: &str = "CAPWAT_SERVER_PORT";
pub const SERVER_WORKERS: &str = "CAPWAT_SERVER_WORKERS";

pub const DB_ENFORCE_TLS: &str = "CAPWAT_DB_ENFORCE_TLS";
pub const DB_CONNECTION_TIMEOUT: &str = "CAPWAT_DB_CONNECTION_TIMEOUT";
pub const DB_IDLE_TIMEOUT: &str = "CAPWAT_DB_IDLE_TIMEOUT";
pub const DB_STATEMENT_TIMEOUT: &str = "CAPWAT_DB_STATEMENT_TIMEOUT";

pub const ADMIN_CLI_DB_URL: &str = "CAPWAT_CLI_DB_URL";
pub const ADMIN_CLI_DB_URL2: &str = "DATABASE_URL";
pub const ADMIN_CLI_DB_USE_TLS: &str = "CAPWAT_CLI_DB_USE_TLS";

pub const HCAPTCHA_SECRET_TOKEN: &str = "CAPWAT_HCAPTCHA_SECRET";
pub const HCAPTCHA_SECRET_TOKEN2: &str = "HCAPTCHA_SECRET";
